export const SetAppLoading = 'app/SetAppLoading'
export const SetVoiceList = 'app/SetVoiceList'
export const SetPlayingVoiceUrl = 'app/SetPlayingVoiceUrl'
export const SetRecording = 'app/SetRecording'
export const SetIsSearch = 'app/SetIsSearch'
export const SetSettingShow = 'app/SetSettingShow'
export const SetSettingItems = 'app/SetSettingItems'
export const SetReFreshPage = 'app/SetReFreshPage'