export const GetTreeGroupsList = 'groupType/GetGroupsList'
export const GetMemberList = 'groupType/GetMemberList'
export const GetTempGroupList = 'groupType/GetTempGroupList'
export const CreatTempGroup = 'groupType/CreatTempGroup'
export const RemoveTempGroup = 'groupType/RemoveTempGroup'

export const SetOriginGroupsList = 'groupType/SetOriginGroupsList'
export const SetMemberList = 'groupType/SetMemberList'
export const SetTreeGroupList = 'groupType/SetTreeGroupList'
export const SetHomeSlectedGroupId = 'groupType/SetHomeSlectedGroupId'
export const SetOpenGroup = 'groupType/SetOpenGroup'
export const SetTempGroupMembers = 'groupType/SetTempGroupMembers'
export const SetSelectedMemberList = 'groupType/SetSelectedMemberList'
export const SetTempGroupList = 'groupType/SetTempGroupList'
export const SetNowStatus = 'groupType/SetNowStatus'
export const SetMyself = 'groupType/SetMyself'
export const SetTreeGroupSelectedList = 'groupType/SetTreeGroupSelectedList'
export const SetGroupTempList = 'groupType/SetGroupTempList'
